language: rust
rust:
 - stable
 - beta
cache: cargo
before_script:
 - cargo update || true
matrix:
  include:
   - rust: stable
     env: TASK=rustfmt
     before_script: rustup component add rustfmt-preview
     script: cargo fmt -- --check
