[package]
name = "warp-ructe"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
ructe = { version = "0.4.0", features = ["sass", "mime03"] }

[dependencies]
warp = "0.1.2"
mime = "0.3.0"
env_logger = "0.5.0"
